/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 1
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 2
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 3
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 4
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 5
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 6
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 7
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 9
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 10
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 11
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 12
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 13
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 14
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 15
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 16
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 17
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 18
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 19
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 20
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 21
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 22
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 23
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 24
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 25
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 26
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 27
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 28
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 29
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 30
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 31
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 32
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 33
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 34
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 35
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 36
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 37
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 38
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 39
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 40
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 41
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 42
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 43
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 44
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 45
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 46
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 47
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 48
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 49
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 50
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 51
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 52
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 53
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 54
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 55
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 56
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 57
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 58
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 59
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 60
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 61
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 62
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 63
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 64
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 65
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 66
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 67
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 68
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 69
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 70
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 71
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 72
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 73
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 74
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 75
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 76
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 77
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 78
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 79
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 80
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 81
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 82
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 83
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 84
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 85
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 86
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 87
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 88
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 89
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 90
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 91
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 92
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 93
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 94
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 95
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 96
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 97
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 98
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 99
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 100
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 101
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 102
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 103
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 104
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 105
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 106
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 107
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 108
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 109
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 110
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 111
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 112
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 113
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 114
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 115
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 116
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 117
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 118
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 119
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 120
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 121
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 122
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 123
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 124
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 125
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 126
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 127
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 128
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 129
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 130
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 131
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 132
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 133
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 134
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 135
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 136
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 137
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 138
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 139
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 140
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 141
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 142
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 143
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 144
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 145
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 146
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 147
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 148
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 149
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 150
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 151
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 152
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 153
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 154
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 155
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 156
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 157
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 158
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 159
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 160
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 161
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 162
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 163
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 164
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 165
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 166
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 167
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 168
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 169
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 170
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 171
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 172
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 173
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 174
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 175
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 176
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 177
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 178
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 179
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 180
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 181
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 182
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 183
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 184
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 185
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 186
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 187
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 188
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 189
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 190
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 191
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 192
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 193
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 194
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 195
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 196
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 197
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 198
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 199
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 200
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 201
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 202
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 203
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 204
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 205
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 206
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 207
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 208
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 209
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 210
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 211
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 212
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 213
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 214
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 215
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 216
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 217
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 218
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 219
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 220
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 221
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 222
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 223
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 224
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 225
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 226
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 227
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 228
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 229
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 230
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 231
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 232
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 233
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 234
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 235
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 236
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 237
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 238
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 239
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 240
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 241
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 242
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 243
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 244
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 245
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 246
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 247
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 248
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 249
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 250
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 251
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 252
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 253
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 254
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 255
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 256
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 257
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 258
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 259
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 260
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 261
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 262
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 263
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 264
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 265
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 266
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 267
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 268
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 269
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 270
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 271
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 272
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 273
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 274
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 275
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 276
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 277
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 278
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 279
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 280
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 281
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 282
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 283
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 284
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 285
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 286
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 287
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 288
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 289
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 290
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 291
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 292
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 293
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 294
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 295
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 296
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 297
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 298
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 299
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 300
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 301
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 302
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 303
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 304
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 305
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 306
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 307
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 308
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 309
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 310
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 311
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 312
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 313
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 314
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 315
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 316
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 317
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 318
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 319
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 320
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 321
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 322
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 323
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 324
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 325
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 326
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 327
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 328
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 329
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 330
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 331
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 332
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 333
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 334
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 335
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 336
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 337
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 338
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 339
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 340
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 341
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 342
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 343
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 344
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 345
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 346
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 347
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 348
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 349
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 350
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 351
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 352
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 353
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 354
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 355
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 356
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 357
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 358
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 359
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 360
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 361
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 362
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 363
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 364
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 365
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 366
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/data_analysis.py --cchpc --gnup 367
