/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 0
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 8
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 481
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 482
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 483
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 485
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 486
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 487
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 488
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 489
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 492
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 493
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 494
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 495
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 496
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 497
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 498
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 499
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 500
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 501
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 502
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 504
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 505
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 507
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 508
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 509
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 510
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 511
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 512
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 513
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 514
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 515
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 516
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 518
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 519
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 520
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 521
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 522
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 523
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 525
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 527
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 528
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 529
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 530
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 531
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 532
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 534
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 535
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 536
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 537
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 538
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 539
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 540
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 541
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 542
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 543
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 546
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 547
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 548
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 549
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 550
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 551
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 552
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 553
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 554
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 555
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 557
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 558
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 559
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 560
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 562
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 563
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 564
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 565
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 566
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 567
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 569
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 570
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 571
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 572
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 573
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 574
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 575
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 576
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 577
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 578
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 579
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 580
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 582
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 583
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 584
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 585
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 586
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 587
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 588
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 589
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 590
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 591
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 593
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 594
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 595
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 596
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 597
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 598
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 599
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 600
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 601
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 602
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 603
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 604
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 605
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 606
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 607
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 608
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 609
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 610
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 611
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 612
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 613
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 614
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 615
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 616
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 617
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 618
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 619
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 620
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 621
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 622
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 623
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 624
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 625
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 626
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 627
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 628
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 629
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 630
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 631
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 632
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 633
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 634
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 635
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 636
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 637
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 638
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 639
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 640
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 641
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 642
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 643
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 644
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 645
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 646
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 647
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 648
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 649
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 650
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 651
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 652
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 653
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 654
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 655
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 656
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 657
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 658
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 659
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 660
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 661
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 662
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 663
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 664
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 665
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 666
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 667
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 668
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 669
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 670
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 671
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 672
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 673
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 674
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 675
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 676
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 677
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 678
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 679
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 680
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 681
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 682
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 683
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 684
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 685
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 686
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 687
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 688
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 689
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 690
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 691
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 692
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 693
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 694
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 695
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 696
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 697
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 698
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 699
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 700
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 701
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 702
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 703
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 704
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 705
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 706
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 707
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 708
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 709
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 710
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 711
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 712
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 713
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 714
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 715
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 716
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 717
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 718
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 719
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 720
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 721
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 722
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 723
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 724
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 725
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 726
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 727
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 728
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 729
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 730
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 731
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 732
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 733
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 734
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 735
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 736
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 737
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 738
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 739
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 740
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 741
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 742
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 743
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 744
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 745
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 746
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 747
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 748
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 749
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 750
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 751
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 752
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 754
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 756
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 757
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 758
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 759
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 760
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 762
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 763
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 764
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 765
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 766
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 768
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 769
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 770
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 771
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 773
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 774
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 775
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 776
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 777
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 778
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 779
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 780
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 781
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 782
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 783
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 784
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 785
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 787
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 789
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 791
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 792
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 793
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 794
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 795
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 796
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 797
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 798
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 799
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 800
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 801
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 802
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 803
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 804
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 805
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 806
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 807
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 808
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 809
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 811
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 812
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 813
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 814
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 815
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 816
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 817
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 818
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 819
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 820
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 821
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 822
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 823
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 824
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 825
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 826
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 827
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 828
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 829
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 830
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 831
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 832
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 833
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 834
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 835
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 836
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 837
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 839
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 840
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 841
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 842
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 844
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 845
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 846
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 849
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 850
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 851
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 852
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 853
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 854
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 855
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 856
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 857
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 858
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 859
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 861
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 862
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 863
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 864
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 865
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 866
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 867
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 870
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 876
