/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 753
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 754
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 755
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 756
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 757
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 758
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 759
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 760
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 761
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 762
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 763
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 764
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 765
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 766
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 767
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 768
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 769
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 770
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 771
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 772
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 773
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 774
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 775
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 776
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 777
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 778
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 779
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 780
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 781
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 782
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 783
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 784
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 785
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 786
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 787
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 788
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 789
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 790
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 791
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 792
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 793
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 794
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 795
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 796
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 797
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 798
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 799
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 800
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 801
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 802
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 803
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 804
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 805
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 806
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 807
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 808
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 809
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 810
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 811
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 812
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 813
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 814
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 815
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 816
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 817
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 818
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 819
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 820
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 821
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 822
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 823
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 824
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 825
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 826
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 827
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 828
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 829
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 830
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 831
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 832
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 833
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 834
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 835
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 836
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 837
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 838
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 839
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 840
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 841
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 842
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 843
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 844
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 845
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 846
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 847
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 848
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 849
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 850
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 851
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 852
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 853
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 854
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 855
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 856
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 857
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 858
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 859
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 860
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 861
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 862
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 863
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 864
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 865
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 866
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 867
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 868
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 869
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 870
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 871
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 872
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 873
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 874
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 875
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 876
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 877
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 878
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 879
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 880
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 881
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 882
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 883
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 884
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 885
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 886
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 887
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 888
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 889
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 890
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 891
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 892
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 893
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 894
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 895
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 896
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 897
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 898
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 899
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 900
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 901
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 902
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 903
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 904
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 905
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 906
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 907
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 908
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 909
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 910
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 911
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 912
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 913
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 914
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 915
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 916
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 917
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 918
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 919
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 920
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 921
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 922
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 923
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 924
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 925
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 926
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 927
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 928
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 929
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 930
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 931
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 932
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 933
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 934
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 935
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 936
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 937
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 938
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 939
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 940
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 941
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 942
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 943
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 944
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 945
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 946
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 947
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 948
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 949
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 950
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 951
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 952
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 953
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 954
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 955
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 956
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 957
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 958
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 959
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 960
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 961
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 962
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 963
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 964
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 965
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 966
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 967
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 968
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 969
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 970
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 971
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 972
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 973
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 974
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 975
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 976
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 977
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 978
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 979
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 980
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 981
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 982
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 983
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 984
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 985
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 986
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 987
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 988
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 989
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 990
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 991
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 992
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 993
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 994
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 995
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 996
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 997
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 998
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 999
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1000
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1001
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1002
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1003
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1004
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1005
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1006
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1007
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1008
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1009
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1010
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1011
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1012
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1013
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1014
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1015
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1016
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1017
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1018
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1019
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1020
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1021
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1022
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1023
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1024
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1025
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1026
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1027
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1028
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1029
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1030
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1031
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1032
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1033
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1034
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1035
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1036
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1037
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1038
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1039
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1040
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1041
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1042
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1043
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1044
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1045
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1046
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1047
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1048
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1049
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1050
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1051
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1052
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1053
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1054
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1055
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1056
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1057
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1058
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1059
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1060
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1061
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1062
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1063
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1064
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1065
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1066
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1067
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1068
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1069
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1070
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1071
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1072
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1073
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1074
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1075
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1076
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1077
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1078
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1079
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1080
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1081
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1082
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1083
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1084
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1085
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1086
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1087
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1088
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1089
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1090
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1091
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1092
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1093
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1094
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1095
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1096
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1097
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1098
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1099
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1100
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1101
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1102
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1103
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1104
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1105
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1106
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1107
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1108
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1109
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1110
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1111
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1112
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1113
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1114
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1115
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1116
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1117
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1118
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1119
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1120
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1121
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1122
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1123
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1124
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1125
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1126
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1127
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1128
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1129
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1130
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1131
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1132
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1133
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1134
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1135
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1136
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1137
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1138
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1139
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1140
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1141
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1142
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1143
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1144
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1145
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1146
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1147
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1148
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1149
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1150
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1151
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1152
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1153
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1154
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1155
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1156
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1157
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1158
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1159
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1160
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1161
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1162
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1163
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1164
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1165
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1166
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1167
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1168
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1169
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1170
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1171
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1172
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1173
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1174
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1175
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1176
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1177
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1178
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1179
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1180
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1181
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1182
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1183
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1184
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1185
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1186
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1187
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1188
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1189
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1190
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1191
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1192
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1193
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1194
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1195
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1196
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1197
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1198
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1199
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1200
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1201
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1202
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1203
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1204
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1205
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1206
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1207
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1208
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1209
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1210
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1211
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1212
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1213
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1214
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1215
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1216
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1217
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1218
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1219
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1220
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1221
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1222
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1223
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1224
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1225
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1226
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1227
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1228
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1229
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1230
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1231
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1232
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1233
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1234
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1235
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1236
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1237
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1238
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1239
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1240
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1241
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1242
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1243
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1244
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1245
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1246
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1247
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1248
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1249
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1250
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1251
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1252
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1253
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1254
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1255
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1256
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1257
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1258
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1259
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1260
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1261
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1262
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1263
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1264
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1265
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1266
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1267
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1268
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1269
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1270
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1271
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1272
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1273
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1274
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1275
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1276
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1277
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1278
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1279
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1280
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1281
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1282
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1283
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1284
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1285
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1286
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1287
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1288
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1289
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1290
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1291
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1292
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1293
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1294
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1295
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1296
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1297
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1298
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1299
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1300
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1301
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1302
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1303
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1304
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1305
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1306
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1307
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1308
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1309
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1310
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1311
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1312
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1313
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1314
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1315
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1316
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1317
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1318
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1319
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1320
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1321
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1322
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1323
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1324
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1325
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1326
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1327
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1328
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1329
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1330
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1331
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1332
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1333
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1334
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1335
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1336
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1337
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1338
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1339
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1340
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1341
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1342
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1343
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1344
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1345
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1346
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1347
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1348
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1349
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1350
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1351
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1352
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1353
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1354
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1355
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1356
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1357
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1358
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1359
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1360
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1361
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1362
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1363
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1364
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1365
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1366
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1367
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1368
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1369
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1370
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1371
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1372
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1373
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1374
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1375
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1376
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1377
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1378
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1379
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1380
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1381
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1382
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1383
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1384
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1385
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1386
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1387
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1388
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1389
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1390
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1391
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1392
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1393
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1394
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1395
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1396
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1397
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1398
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1399
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1400
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1401
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1402
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1403
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1404
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1405
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1406
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1407
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1408
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1409
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1410
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1411
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1412
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1413
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1414
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1415
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1416
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1417
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1418
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1419
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1420
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1421
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1422
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1423
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1424
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1425
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1426
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1427
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1428
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1429
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1430
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1431
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1432
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1433
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1434
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1435
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1436
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1437
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1438
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1439
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1440
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1441
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1442
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1443
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1444
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1445
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1446
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1447
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1448
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1449
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1450
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1451
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1452
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1453
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1454
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1455
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1456
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1457
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1458
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1459
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1460
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1461
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1462
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1463
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1464
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1465
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1466
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1467
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1468
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1469
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1470
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1471
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1472
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1473
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1474
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1475
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1476
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1477
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1478
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1479
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1480
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1481
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1482
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1483
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1484
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1485
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1486
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1487
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1488
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1489
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1490
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1491
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1492
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1493
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1494
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1495
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1496
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1497
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1498
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1499
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1500
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1501
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1502
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1503
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1504
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1505
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1506
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1507
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1508
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1509
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1510
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1511
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1512
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1513
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1514
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1515
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1516
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1517
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1518
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1519
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1520
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1521
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1522
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1523
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1524
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1525
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1526
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1527
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1528
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1529
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1530
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1531
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1532
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1533
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1534
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/generate_matrix.py --cchpc --gnup 1535
