/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 1
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 2
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 3
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 4
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 5
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 6
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 7
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 9
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 10
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 11
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 12
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 13
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 14
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 15
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 16
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 17
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 18
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 19
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 20
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 21
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 22
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 23
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 24
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 25
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 26
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 27
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 28
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 29
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 30
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 31
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 32
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 33
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 34
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 35
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 36
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 37
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 38
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 39
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 40
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 41
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 42
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 43
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 44
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 45
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 46
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 47
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 48
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 49
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 50
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 51
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 52
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 53
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 54
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 55
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 56
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 57
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 58
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 59
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 60
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 61
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 62
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 63
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 64
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 65
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 66
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 67
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 68
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 69
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 70
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 71
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 72
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 73
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 74
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 75
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 76
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 77
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 78
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 79
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 80
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 81
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 82
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 83
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 84
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 85
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 86
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 87
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 88
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 89
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 90
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 91
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 92
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 93
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 94
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 95
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 96
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 97
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 98
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 99
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 100
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 101
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 102
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 103
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 104
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 105
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 106
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 107
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 108
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 109
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 110
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 111
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 112
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 113
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 114
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 115
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 116
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 117
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 118
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 119
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 120
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 121
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 122
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 123
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 124
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 125
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 126
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 127
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 128
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 129
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 130
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 131
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 132
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 133
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 134
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 135
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 136
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 137
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 138
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 139
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 140
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 141
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 142
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 143
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 144
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 145
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 146
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 147
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 148
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 149
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 150
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 151
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 152
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 153
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 154
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 155
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 156
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 157
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 158
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 159
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 160
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 161
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 162
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 163
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 164
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 165
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 166
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 167
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 168
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 169
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 170
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 171
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 172
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 173
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 174
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 175
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 176
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 177
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 178
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 179
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 180
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 181
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 182
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 183
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 184
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 185
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 186
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 187
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 188
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 189
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 190
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 191
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 192
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 193
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 194
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 195
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 196
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 197
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 198
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 199
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 200
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 201
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 202
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 203
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 204
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 205
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 206
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 207
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 208
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 209
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 210
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 211
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 212
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 213
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 214
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 215
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 216
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 217
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 218
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 219
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 220
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 221
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 222
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 223
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 224
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 225
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 226
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 227
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 228
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 229
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 230
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 231
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 232
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 233
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 234
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 235
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 236
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 237
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 238
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 239
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 240
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 241
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 242
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 243
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 244
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 245
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 246
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 247
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 248
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 249
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 250
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 251
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 252
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 253
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 254
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 255
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 256
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 257
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 258
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 259
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 260
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 261
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 262
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 263
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 264
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 265
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 266
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 267
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 268
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 269
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 270
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 271
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 272
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 273
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 274
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 275
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 276
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 277
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 278
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 279
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 280
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 281
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 282
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 283
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 284
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 285
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 286
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 287
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 288
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 289
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 290
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 291
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 292
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 293
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 294
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 295
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 296
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 297
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 298
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 299
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 300
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 301
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 302
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 303
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 304
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 305
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 306
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 307
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 308
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 309
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 310
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 311
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 312
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 313
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 314
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 315
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 316
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 317
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 318
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 319
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 320
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 321
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 322
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 323
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 324
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 325
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 326
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 327
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 328
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 329
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 330
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 331
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 332
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 333
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 334
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 335
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 336
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 337
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 338
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 339
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 340
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 341
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 342
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 343
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 344
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 345
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 346
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 347
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 348
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 349
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 350
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 351
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 352
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 353
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 354
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 355
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 356
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 357
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 358
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 359
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 360
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 361
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 362
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 363
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 364
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 365
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 366
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/inversion.py --cchpc --read --gnup 367
