/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 1
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 2
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 3
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 4
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 5
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 6
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 7
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 9
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 10
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 11
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 12
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 13
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 14
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 15
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 16
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 17
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 18
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 19
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 20
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 21
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 22
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 23
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 24
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 25
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 26
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 27
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 28
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 29
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 30
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 31
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 32
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 33
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 34
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 35
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 36
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 37
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 38
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 39
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 40
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 41
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 42
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 43
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 44
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 45
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 46
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 47
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 48
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 49
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 50
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 51
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 52
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 53
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 54
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 55
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 56
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 57
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 58
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 59
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 60
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 61
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 62
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 63
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 64
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 65
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 66
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 67
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 68
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 69
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 70
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 71
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 72
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 73
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 74
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 75
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 76
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 77
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 78
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 79
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 80
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 81
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 82
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 83
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 84
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 85
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 86
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 87
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 88
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 89
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 90
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 91
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 92
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 93
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 94
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 95
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 96
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 97
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 98
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 99
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 100
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 101
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 102
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 103
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 104
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 105
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 106
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 107
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 108
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 109
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 110
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 111
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 112
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 113
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 114
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 115
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 116
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 117
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 118
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 119
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 120
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 121
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 122
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 123
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 124
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 125
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 126
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 127
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 128
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 129
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 130
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 131
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 132
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 133
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 134
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 135
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 136
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 137
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 138
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 139
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 140
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 141
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 142
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 143
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 144
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 145
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 146
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 147
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 148
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 149
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 150
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 151
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 152
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 153
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 154
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 155
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 156
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 157
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 158
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 159
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 160
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 161
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 162
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 163
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 164
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 165
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 166
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 167
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 168
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 169
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 170
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 171
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 172
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 173
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 174
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 175
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 176
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 177
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 178
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 179
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 180
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 181
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 182
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 183
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 184
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 185
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 186
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 187
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 188
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 189
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 190
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 191
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 192
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 193
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 194
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 195
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 196
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 197
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 198
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 199
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 200
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 201
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 202
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 203
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 204
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 205
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 206
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 207
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 208
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 209
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 210
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 211
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 212
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 213
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 214
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 215
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 216
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 217
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 218
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 219
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 220
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 221
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 222
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 223
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 224
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 225
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 226
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 227
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 228
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 229
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 230
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 231
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 232
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 233
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 234
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 235
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 236
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 237
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 238
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 239
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 240
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 241
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 242
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 243
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 244
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 245
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 246
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 247
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 248
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 249
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 250
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 251
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 252
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 253
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 254
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 255
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 256
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 257
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 258
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 259
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 260
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 261
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 262
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 263
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 264
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 265
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 266
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 267
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 268
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 269
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 270
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 271
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 272
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 273
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 274
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 275
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 276
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 277
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 278
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 279
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 280
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 281
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 282
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 283
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 284
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 285
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 286
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 287
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 288
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 289
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 290
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 291
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 292
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 293
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 294
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 295
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 296
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 297
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 298
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 299
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 300
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 301
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 302
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 303
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 304
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 305
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 306
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 307
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 308
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 309
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 310
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 311
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 312
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 313
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 314
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 315
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 316
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 317
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 318
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 319
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 320
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 321
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 322
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 323
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 324
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 325
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 326
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 327
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 328
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 329
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 330
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 331
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 332
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 333
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 334
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 335
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 336
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 337
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 338
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 339
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 340
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 341
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 342
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 343
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 344
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 345
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 346
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 347
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 348
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 349
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 350
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 351
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 352
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 353
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 354
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 355
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 356
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 357
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 358
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 359
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 360
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 361
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 362
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 363
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 364
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 365
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 366
/home/g.samarth/anaconda3/envs/py3/bin/python /home/g.samarth/dopplervel2/hathaway.py --hpc --gnup 367
