/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 0 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 1 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 2 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 3 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 4 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 5 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 6 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 7 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 8 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 9 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 10 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 11 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 12 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 13 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 14 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 15 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 16 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 17 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 18 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 19 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 20 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 21 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 22 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 23 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 24 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 25 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 26 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 27 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 28 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 29 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 30 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 31 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 32 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 33 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 34 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 35 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 36 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 37 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 38 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 39 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 40 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 41 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 42 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 43 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 44 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 45 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 46 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 47 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 48 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 49 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 50 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 51 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 52 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 53 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 54 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 55 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 56 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 57 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 58 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 59 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 60 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 61 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 62 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 63 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 64 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 65 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 66 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 67 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 68 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 69 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 70 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 71 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 72 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 73 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 74 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 75 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 76 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 77 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 78 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 79 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 80 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 81 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 82 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 83 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 84 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 85 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 86 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 87 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 88 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 89 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 90 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 91 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 92 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 93 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 94 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 95 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 96 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 97 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 98 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 99 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 100 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 101 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 102 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 103 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 104 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 105 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 106 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 107 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 108 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 109 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 110 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 111 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 112 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 113 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 114 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 115 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 116 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 117 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 118 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 119 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 120 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 121 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 122 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 123 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 124 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 125 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 126 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 127 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 128 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 129 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 130 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 131 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 132 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 133 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 134 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 135 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 136 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 137 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 138 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 139 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 140 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 141 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 142 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 143 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 144 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 145 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 146 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 147 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 148 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 149 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 150 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 151 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 152 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 153 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 154 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 155 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 156 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 157 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 158 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 159 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 160 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 161 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 162 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 163 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 164 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 165 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 166 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 167 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 168 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 169 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 170 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 171 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 172 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 173 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 174 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 175 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 176 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 177 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 178 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 179 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 180 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 181 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 182 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 183 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 184 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 185 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 186 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 187 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 188 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 189 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 190 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 191 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 192 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 193 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 194 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 195 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 196 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 197 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 198 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 199 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 200 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 201 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 202 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 203 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 204 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 205 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 206 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 207 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 208 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 209 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 210 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 211 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 212 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 213 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 214 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 215 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 216 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 217 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 218 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 219 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 220 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 221 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 222 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 223 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 224 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 225 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 226 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 227 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 228 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 229 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 230 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 231 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 232 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 233 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 234 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 235 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 236 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 237 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 238 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 239 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 240 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 241 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 242 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 243 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 244 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 245 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 246 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 247 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 248 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 249 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 250 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 251 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 252 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 253 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 254 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 255 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 256 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 257 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 258 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 259 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 260 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 261 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 262 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 263 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 264 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 265 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 266 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 267 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 268 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 269 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 270 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 271 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 272 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 273 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 274 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 275 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 276 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 277 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 278 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 279 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 280 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 281 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 282 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 283 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 284 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 285 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 286 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 287 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 288 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 289 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 290 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 291 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 292 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 293 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 294 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 295 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 296 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 297 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 298 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 299 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 300 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 301 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 302 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 303 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 304 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 305 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 306 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 307 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 308 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 309 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 310 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 311 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 312 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 313 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 314 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 315 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 316 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 317 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 318 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 319 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 320 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 321 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 322 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 323 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 324 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 325 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 326 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 327 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 328 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 329 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 330 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 331 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 332 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 333 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 334 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 335 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 336 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 337 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 338 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 339 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 340 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 341 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 342 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 343 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 344 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 345 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 346 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 347 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 348 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 349 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 350 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 351 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 352 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 353 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 354 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 355 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 356 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 357 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 358 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 359 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 360 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 361 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 362 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 363 --chris
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 364 --chris
