/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 1
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 2
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 3
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 4
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 5
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 6
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 7
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 9
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 10
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 11
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 12
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 13
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 14
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 15
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 16
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 17
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 18
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 19
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 20
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 21
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 22
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 23
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 24
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 25
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 26
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 27
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 28
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 29
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 30
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 31
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 32
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 33
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 34
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 35
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 36
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 37
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 38
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 39
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 40
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 41
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 42
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 43
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 44
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 45
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 46
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 47
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 48
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 49
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 50
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 51
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 52
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 53
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 54
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 55
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 56
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 57
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 58
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 59
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 60
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 61
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 62
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 63
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 64
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 65
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 66
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 67
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 68
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 69
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 70
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 71
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 72
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 73
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 74
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 75
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 76
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 77
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 78
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 79
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 80
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 81
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 82
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 83
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 84
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 85
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 86
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 87
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 88
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 89
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 90
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 91
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 92
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 93
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 94
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 95
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 96
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 97
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 98
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 99
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 100
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 101
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 102
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 103
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 104
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 105
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 106
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 107
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 108
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 109
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 110
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 111
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 112
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 113
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 114
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 115
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 116
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 117
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 118
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 119
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 120
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 121
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 122
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 123
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 124
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 125
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 126
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 127
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 128
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 129
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 130
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 131
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 132
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 133
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 134
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 135
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 136
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 137
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 138
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 139
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 140
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 141
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 142
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 143
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 144
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 145
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 146
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 147
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 148
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 149
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 150
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 151
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 152
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 153
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 154
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 155
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 156
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 157
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 158
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 159
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 160
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 161
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 162
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 163
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 164
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 165
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 166
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 167
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 168
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 169
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 170
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 171
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 172
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 173
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 174
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 175
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 176
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 177
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 178
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 179
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 180
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 181
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 182
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 183
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 184
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 185
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 186
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 187
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 188
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 189
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 190
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 191
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 192
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 193
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 194
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 195
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 196
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 197
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 198
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 199
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 200
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 201
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 202
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 203
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 204
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 205
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 206
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 207
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 208
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 209
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 210
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 211
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 212
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 213
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 214
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 215
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 216
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 217
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 218
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 219
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 220
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 221
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 222
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 223
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 224
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 225
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 226
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 227
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 228
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 229
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 230
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 231
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 232
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 233
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 234
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 235
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 236
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 237
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 238
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 239
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 240
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 241
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 242
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 243
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 244
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 245
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 246
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 247
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 248
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 249
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 250
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 251
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 252
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 253
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 254
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 255
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 256
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 257
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 258
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 259
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 260
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 261
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 262
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 263
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 264
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 265
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 266
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 267
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 268
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 269
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 270
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 271
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 272
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 273
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 274
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 275
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 276
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 277
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 278
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 279
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 280
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 281
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 282
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 283
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 284
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 285
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 286
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 287
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 288
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 289
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 290
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 291
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 292
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 293
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 294
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 295
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 296
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 297
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 298
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 299
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 300
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 301
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 302
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 303
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 304
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 305
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 306
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 307
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 308
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 309
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 310
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 311
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 312
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 313
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 314
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 315
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 316
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 317
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 318
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 319
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 320
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 321
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 322
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 323
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 324
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 325
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 326
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 327
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 328
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 329
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 330
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 331
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 332
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 333
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 334
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 335
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 336
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 337
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 338
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 339
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 340
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 341
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 342
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 343
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 344
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 345
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 346
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 347
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 348
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 349
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 350
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 351
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 352
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 353
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 354
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 355
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 356
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 357
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 358
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 359
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 360
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 361
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 362
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 363
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 364
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 365
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 366
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/rotation.py --gnup 367
