/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190101
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190102
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190103
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190104
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190105
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190106
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190107
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190108
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190109
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190110
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190111
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190112
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190113
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190114
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190115
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190116
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190117
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190118
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190119
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190120
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190121
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190122
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190123
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190124
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190125
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190126
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190127
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190128
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190129
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190130
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190131
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190201
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190202
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190203
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190204
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190205
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190206
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190207
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190208
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190209
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190210
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190211
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190212
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190213
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190214
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190215
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190216
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190217
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190218
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190219
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190220
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190221
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190222
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190223
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190224
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190225
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190226
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190227
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190228
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190301
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190302
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190303
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190304
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190305
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190306
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190307
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190308
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190309
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190310
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190311
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190312
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190313
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190314
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190315
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190316
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190317
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190318
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190319
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190320
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190321
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190322
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190323
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190324
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190325
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190326
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190327
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190328
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190329
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190330
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190331
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190401
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190402
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190403
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190404
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190405
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190406
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190407
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190408
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190409
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190410
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190411
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190412
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190413
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190414
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190415
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190416
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190417
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190418
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190419
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190420
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190421
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190422
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190423
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190424
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190425
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190426
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190427
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190428
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190429
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190430
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190501
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190502
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190503
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190504
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190505
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190506
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190507
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190508
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190509
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190510
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190511
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190512
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190513
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190514
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190515
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190516
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190517
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190518
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190519
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190520
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190521
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190522
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190523
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190524
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190525
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190526
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190527
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190528
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190529
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190530
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190531
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190601
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190602
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190603
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190604
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190605
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190606
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190607
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190608
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190609
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190610
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190611
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190612
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190613
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190614
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190615
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190616
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190617
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190618
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190619
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190620
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190621
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190622
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190623
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190624
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190625
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190626
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190627
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190628
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190629
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190630
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190701
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190702
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190703
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190704
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190705
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190706
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190707
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190708
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190709
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190710
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190711
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190712
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190713
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190714
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190715
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190716
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190717
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190718
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190719
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190720
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190721
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190722
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190723
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190724
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190725
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190726
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190727
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190728
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190729
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190730
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190731
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190801
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190802
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190803
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190804
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190805
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190806
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190807
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190808
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190809
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190810
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190811
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190812
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190813
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190814
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190815
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190816
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190817
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190818
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190819
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190820
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190821
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190822
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190823
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190824
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190825
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190826
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190827
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190828
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190829
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190830
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190901
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190902
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190903
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190904
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190905
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190906
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190907
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190908
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190909
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190910
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190911
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190912
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190913
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190914
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190915
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190916
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190917
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190918
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190919
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190920
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190921
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190922
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190923
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190924
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190925
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190926
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190927
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190928
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190929
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190930
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/get_vec_mag_spectra.py --gnup 20190931
