/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 0
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 1
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 2
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 3
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 4
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 5
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 6
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 7
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 8
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 9
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 10
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 11
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 12
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 13
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 14
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 15
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 16
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 17
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 18
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 19
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 20
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 21
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 22
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 23
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 24
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 25
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 26
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 27
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 28
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 29
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 30
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 31
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 32
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 33
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 34
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 35
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 36
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 37
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 38
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 39
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 40
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 41
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 42
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 43
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 44
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 45
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 46
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 47
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 48
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 49
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 50
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 51
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 52
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 53
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 54
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 55
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 56
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 57
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 58
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 59
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 60
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 61
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 62
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 63
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 64
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 65
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 66
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 67
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 68
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 69
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 70
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 71
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 72
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 73
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 74
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 75
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 76
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 77
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 78
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 79
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 80
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 81
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 82
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 83
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 84
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 85
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 86
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 87
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 88
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 89
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 90
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 91
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 92
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 93
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 94
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 95
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 96
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 97
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 98
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 99
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 100
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 101
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 102
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 103
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 104
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 105
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 106
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 107
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 108
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 109
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 110
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 111
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 112
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 113
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 114
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 115
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 116
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 117
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 118
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 119
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 120
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 121
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 122
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 123
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 124
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 125
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 126
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 127
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 128
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 129
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 130
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 131
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 132
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 133
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 134
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 135
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 136
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 137
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 138
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 139
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 140
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 141
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 142
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 143
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 144
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 145
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 146
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 147
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 148
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 149
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 150
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 151
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 152
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 153
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 154
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 155
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 156
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 157
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 158
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 159
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 160
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 161
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 162
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 163
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 164
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 165
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 166
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 167
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 168
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 169
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 170
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 171
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 172
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 173
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 174
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 175
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 176
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 177
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 178
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 179
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 180
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 181
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 182
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 183
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 184
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 185
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 186
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 187
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 188
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 189
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 190
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 191
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 192
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 193
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 194
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 195
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 196
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 197
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 198
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 199
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 200
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 201
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 202
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 203
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 204
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 205
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 206
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 207
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 208
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 209
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 210
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 211
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 212
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 213
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 214
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 215
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 216
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 217
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 218
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 219
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 220
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 221
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 222
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 223
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 224
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 225
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 226
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 227
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 228
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 229
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 230
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 231
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 232
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 233
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 234
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 235
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 236
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 237
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 238
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 239
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 240
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 241
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 242
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 243
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 244
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 245
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 246
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 247
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 248
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 249
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 250
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 251
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 252
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 253
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 254
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 255
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 256
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 257
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 258
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 259
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 260
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 261
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 262
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 263
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 264
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 265
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 266
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 267
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 268
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 269
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 270
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 271
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 272
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 273
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 274
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 275
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 276
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 277
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 278
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 279
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 280
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 281
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 282
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 283
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 284
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 285
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 286
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 287
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 288
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 289
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 290
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 291
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 292
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 293
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 294
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 295
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 296
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 297
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 298
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 299
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 300
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 301
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 302
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 303
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 304
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 305
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 306
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 307
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 308
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 309
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 310
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 311
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 312
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 313
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 314
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 315
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 316
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 317
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 318
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 319
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 320
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 321
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 322
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 323
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 324
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 325
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 326
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 327
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 328
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 329
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 330
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 331
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 332
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 333
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 334
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 335
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 336
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 337
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 338
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 339
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 340
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 341
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 342
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 343
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 344
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 345
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 346
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 347
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 348
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 349
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 350
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 351
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 352
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 353
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 354
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 355
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 356
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 357
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 358
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 359
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 360
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 361
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 362
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 363
/home/g.samarth/anaconda3/bin/python /home/g.samarth/dopplervel2/lct_process.py --year 2010 --daynum 364
