#!/bin/sh
#PBS -N HMIprocessImg
#PBS -o /home/g.samarth/dopplervel2/opimg.log
#PBS -e /home/g.samarth/dopplervel2/erimg.log
#PBS -l select=1:ncpus=6
#PBS -q small
cd $PBS_O_WORKDIR
echo $PBS_JOBID
export TERM=xterm
echo "Starting at "`date`
/opt/pbs/bin/pbsdsh $PBS_O_WORKDIR/test2.sh
#/opt/pbs/bin/pbsdsh `$HOME/anaconda3/envs/py3/bin/python $PBS_O_WORKDIR/hathaway.py --hpc --job`
echo "Finished at "`date`
